### ISSUE TITLE
mysql parenthesis around UNION

### ISSUE THREAD

**Issue by ghazel** [rails/arel#341]
Related to #58 #299 and maybe #158

```
bundle show | grep arel
  * arel (5.0.1.20140414130214)
```

``` ruby
q1 = User.where("id < 10").order("id desc")
q2 = User.where("id > 20").order("id asc")
union = q1.union(q2)
User.from(User.arel_table.create_table_alias(union, 'users'))
D, [2014-12-02T12:50:52.537354 #29904] DEBUG -- :   User Load (0.3ms)  SELECT `users`.* FROM ( SELECT `users`.* FROM `users`  WHERE (id < 10)  ORDER BY id desc UNION SELECT `users`.* FROM `users`  WHERE (id > 20)  ORDER BY id asc ) `users`
E, [2014-12-02T12:50:52.537493 #29904] ERROR -- : Mysql2::Error: Incorrect usage of UNION and ORDER BY: SELECT `users`.* FROM ( SELECT `users`.* FROM `users`  WHERE (id < 10)  ORDER BY id desc UNION SELECT `users`.* FROM `users`  WHERE (id > 20)  ORDER BY id asc ) `users`
```

Correct syntax would be:

``` sql
SELECT `users`.* FROM (( SELECT `users`.* FROM `users`  WHERE (id < 10)  ORDER BY id desc) UNION (SELECT `users`.* FROM `users`  WHERE (id > 20)  ORDER BY id asc )) `users`
```

**Comment by vovimayhem** [comment]
+1

**Comment by Prizrack13** [comment]
Looks like it was fixed for mysql but not for postgres
https://github.com/rails/arel/commit/2567b72f9582c14a591156653e2b656d48200b11

**Comment by mhuggins** [comment]
This still appears to be an issue in postgres, which makes chained unions/intersections not work for common table expressions.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Comment by kbrock** [comment]
Fix merged into Rails
